services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: quotes_API
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
  
  crear_tabla:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
    - postgres
    command: python crear_tabla.py
    restart: on-failure

  debezium:
    image: debezium/connect:2.7.3.Final
    restart: always
    container_name: debezium
    depends_on:
      - postgres
    ports:
      - "8084:8083"
    environment:
      - BOOTSTRAP_SERVERS=34.52.238.189:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - ENABLE_DEBEZIUM_SCRIPTING=true

  debezium-ui:
    image: debezium/debezium-ui:latest
    restart: always
    container_name: debezium-ui
    hostname: debezium-ui
    depends_on:
      - debezium
    ports:
      - '8080:8080'
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
